#!/bin/bash

: ${USER:=sync}
: ${UID:=501}
: ${GROUP:=sync}
: ${GID:=501}
: ${SRC:=/source}
: ${DST:=/destination}

: ${VERBOSE:=false}
: ${INIT_SYNC:=false}
: ${INIT_SYNC_DIR:=/shared}
: ${INIT_SYNC_FINISHED_FILE:=init_done}
: ${UNISON_MAX_THREADS:=10}

rm -rf $INIT_SYNC_DIR/$INIT_SYNC_FINISHED_FILE

generate_unison_prf() {
	filename="$1"
	: {$2:=true}
	watch=""
	if [ $2 == true ]; then
		watch="repeat=watch"
	fi;

	echo "
	root = $SRC
	root = $DST

	auto=true
	backups=false
	batch=true
	contactquietly=true
	fastcheck=true
	maxthreads=$UNISON_MAX_THREADS
	nodeletion=$SRC
	prefer=newer
	$watch
	silent=$VERBOSE

	ignore = Path .git/*
	ignore = Path .idea/*

	$UNISON_ADDITIONAL_CONFIG

	" > ${HOME}/.unison/$filename.prf
}

if ! id -u $USER > /dev/null 2>&1; then
	getent group $GID
	if [ "?$" != "2" ]; then
		gname=`getent group $GID | cut -d: -f1`
		groupmod -g 9999 $gname
	fi;

	addgroup -g $GID -S $GROUP
	adduser -u $UID -D -S -G $GROUP $USER
fi;

chown $USER:$GROUP $SRC
chown $USER:$GROUP $DST
chown $USER:$GROUP $INIT_SYNC_DIR

HOME=$(getent passwd "$USER" | cut -d: -f6)

if [ -n "$INOTIFY_WATCHES" ]; then
	echo fs.inotify.max_user_watches=$INOTIFY_WATCHES >> /etc/sysctl.conf && sysctl -p
fi;

mkdir -p $HOME/.unison
chown -R $USER:$GROUP $HOME/.unison

generate_unison_prf sync true
generate_unison_prf init false

command=""
if [ $INIT_SYNC == true ]; then
	command="unison init; touch $INIT_SYNC_DIR/$INIT_SYNC_FINISHED_FILE && "
fi;

command="$command unison sync"

su -c "$command" -s /bin/bash $USER

cat $HOME/.unison/sync.prf

